/** 唯一可执行清单；bundles 指定每例需要的本地构建产物。 */
export const cases = [
  { id: 'list-basic', purpose: '列表表头、固定数据与单元格绘制', file: './table/list-basic.mjs', bundles: ['vtable'] },
  { id: 'list-select-cell', purpose: '点击单元格后选择范围确实改变', file: './table/list-select-cell.mjs', bundles: ['vtable'] },
  { id: 'pivot-analysis-two-level', purpose: '两级维度与双指标透视数据分析', file: './pivot/analysis-two-level.mjs', bundles: ['vtable'] },
  { id: 'gantt-taskbar-relative-rect', purpose: '项目子任务与空任务的相对矩形', file: './gantt/taskbar-relative-rect.mjs', bundles: ['gantt'] },
  { id: 'sheet-add-columns', purpose: 'Sheet 公式与列插入', file: './sheet/add-columns.mjs', bundles: ['sheet'] },
  { id: 'wrapped-text', purpose: '格式化文本自动换行与显式换行', file: './cells/wrapped-text.mjs', bundles: ['vtable'] },
  { id: 'checkbox-states', purpose: '复选框状态组合', file: './cells/checkbox-states.mjs', bundles: ['vtable'] },
  { id: 'mixed-sparkline-progress', purpose: '动态单元格类型与负值进度条', file: './cells/mixed-sparkline-progress.mjs', bundles: ['vtable'] },
  { id: 'switch-button', purpose: '开关和按钮普通与禁用状态', file: './cells/switch-button.mjs', bundles: ['vtable'] },
  { id: 'level-span', purpose: '多层表头 levelSpan', file: './header/level-span.mjs', bundles: ['vtable'] },
  { id: 'initial-desc', purpose: '自定义比较器与初始降序', file: './sort/initial-desc.mjs', bundles: ['vtable'] },
  { id: 'theme-arco', purpose: 'ARCO 主题与自动行高', file: './theme/arco.mjs', bundles: ['vtable'] },
  { id: 'auto-width-height', purpose: '列宽与行高自动测量', file: './layout/auto-width-height.mjs', bundles: ['vtable'] },
  { id: 'merge-cells', purpose: '相邻单元格合并与动态样式', file: './header/merge-cells.mjs', bundles: ['vtable'] },
  { id: 'plugin-filter-hide-reorder', purpose: '筛选插件与隐藏及移动列', file: './plugins/filter-hide-reorder.mjs', bundles: ['plugins'] },
  { id: 'pivot-chart-box-plot', purpose: '透视箱线图和离群点', file: './pivot-chart/box-plot.mjs', bundles: ['vchart'] },
  { id: 'row-series-number', purpose: '独立行序号列', file: './header/row-series-number.mjs', bundles: ['vtable'] },
  { id: 'scroll-bar-to-side', purpose: '滚动条贴边与多层表头', file: './scroll/bar-to-side.mjs', bundles: ['vtable'] },
  { id: 'gantt-baseline-bottom', purpose: 'Gantt 基线与三级时间轴', file: './gantt/baseline-bottom.mjs', bundles: ['gantt'] },
  { id: 'select-highlight-row', purpose: '选择高亮 row', file: './interaction/select-highlight-row.mjs', bundles: ['vtable'] },
  { id: 'select-highlight-column', purpose: '选择高亮 column', file: './interaction/select-highlight-column.mjs', bundles: ['vtable'] },
  { id: 'select-highlight-cross-theme', purpose: '选择高亮 cross 主题', file: './interaction/select-highlight-cross-theme.mjs', bundles: ['vtable'] },
  { id: 'select-highlight-cross-header-cell', purpose: '选择高亮 cross 主题 表头单格', file: './interaction/select-highlight-cross-header-cell.mjs', bundles: ['vtable'] },
  { id: 'select-highlight-cross-transpose', purpose: '选择高亮 cross 主题 表头单格 转置', file: './interaction/select-highlight-cross-transpose.mjs', bundles: ['vtable'] },
  { id: 'select-cross', purpose: 'cross 模式表体与表头连续选择', file: './interaction/select-cross.mjs', bundles: ['vtable'] },
  { id: 'list-empty-resize', purpose: '空表在缩小视口中绘制', file: './empty/list-resize.mjs', bundles: ['vtable'] },
  { id: 'edit-start-with-value', purpose: '输入编辑器启动初始值', file: './edit/start-with-value.mjs', bundles: ['editors'] },
  { id: 'pivot-corner-without-rows', purpose: '无行无指标的强制角头', file: './pivot/corner-without-rows.mjs', bundles: ['vtable'] },
  { id: 'aggregation-pagination', purpose: '合并、SUM 聚合与分页', file: './analysis/aggregation-pagination.mjs', bundles: ['vtable'] },
  { id: 'update-merged-records', purpose: '合并分组中的记录更新', file: './records/update-merged.mjs', bundles: ['vtable'] },
  { id: 'transpose-theme-header', purpose: '转置分组表头与扩展主题', file: './transpose/theme-header.mjs', bundles: ['vtable'] },
  { id: 'progress-custom-layout', purpose: '动态图标、进度条与自定义布局', file: './custom/progress-layout.mjs', bundles: ['vtable'] },
  { id: 'component-title', purpose: '标题、副标题和表头点击', file: './components/title.mjs', bundles: ['vtable'] },
  { id: 'aggregation-float', purpose: '浮点 AVG 与顶部 SUM 聚合', file: './analysis/aggregation-float.mjs', bundles: ['vtable'] },
  { id: 'filter-api', purpose: '字段与函数过滤器交集', file: './analysis/filter-api.mjs', bundles: ['vtable'] },
  { id: 'frozen-right-bottom', purpose: '左右与底部冻结边界组合', file: './frozen/right-bottom.mjs', bundles: ['vtable'] },
  { id: 'pivot-empty-tip', purpose: '无数据透视表空状态', file: './empty/pivot-tip.mjs', bundles: ['vtable'] },
  { id: 'cyrillic-wrap', purpose: '西里尔字母与混合文本换行', file: './language/cyrillic-wrap.mjs', bundles: ['vtable'] },
  { id: 'adaptive-width', purpose: 'adaptive 列宽填充', file: './layout/adaptive-width.mjs', bundles: ['vtable'] },
  { id: 'pivot-virtual-column-total', purpose: '虚拟列节点与行列合计', file: './pivot/virtual-column-total.mjs', bundles: ['vtable'] },
  { id: 'sheet-formula-edit', purpose: 'Sheet 多区域公式与编辑', file: './sheet/formula-edit.mjs', bundles: ['sheet'] },
  { id: 'gantt-baseline-top', purpose: 'Gantt 任务条上方基线', file: './gantt/baseline-top.mjs', bundles: ['gantt'] },
  { id: 'tree-list-merge-expand', purpose: '树形列表与合并列展开', file: './tree/list-merge-expand.mjs', bundles: ['vtable'] },
  { id: 'sort-update-state', purpose: 'setRecords 后切换排序状态', file: './sort/update-state.mjs', bundles: ['vtable'] },
  { id: 'records-add-merged', purpose: '合并分组插入记录', file: './records/add-merged.mjs', bundles: ['vtable'] },
  { id: 'records-delete-merged', purpose: '合并分组删除记录', file: './records/delete-merged.mjs', bundles: ['vtable'] },
  { id: 'nested-field', purpose: '数组字段路径与缺失值', file: './data/nested-field.mjs', bundles: ['vtable'] },
  { id: 'promise-source', purpose: '异步 CachedDataSource 批次加载', file: './data/promise-source.mjs', bundles: ['vtable'] },
  { id: 'plugin-highlight-header', purpose: '透视表选择后的行列表头高亮', file: './plugins/highlight-header.mjs', bundles: ['plugins'] },
  { id: 'pivot-update-filter', purpose: '透视表过滤规则更新', file: './pivot/update-filter.mjs', bundles: ['vtable'] },
  { id: 'inline-image', purpose: '图片单元格边缘点击与自动尺寸', file: './cells/inline-image.mjs', bundles: ['vtable'] },
  { id: 'hover-tooltip', purpose: '多单元格悬停提示更新', file: './components/hover-tooltip.mjs', bundles: ['vtable'] },
  { id: 'menu-disabled-item', purpose: '下拉子菜单禁用项', file: './menu/disabled-item.mjs', bundles: ['vtable'] },
  { id: 'pivot-indicator-sort-rule', purpose: '透视指标排序规则和背景映射', file: './pivot/indicator-sort-rule.mjs', bundles: ['vtable'] },
  { id: 'pivot-custom-sort-click-colors', purpose: '透视自定义比较器点击排序及双指标着色', file: './pivot/custom-sort-click-colors.mjs', bundles: ['vtable'] },
  { id: 'key-size-config', purpose: '稳定 key 的列宽行高配置', file: './layout/key-size-config.mjs', bundles: ['vtable'] },
  { id: 'style-dashed-border', purpose: '虚线双色单元格边框', file: './style/dashed-border.mjs', bundles: ['vtable'] },
  { id: 'group-one-column', purpose: '隐藏分组字段的单列列表', file: './group/one-column.mjs', bundles: ['vtable'] },
  { id: 'api-update-columns', purpose: '悬停时更新列', file: './api/update-columns.mjs', bundles: ['vtable'] },
  { id: 'disable-hover-columns', purpose: '列级禁用表体和表头悬停', file: './interaction/disable-hover-columns.mjs', bundles: ['vtable'] },
  { id: 'select-highlight-in-range', purpose: '跨表头与表体拖选范围高亮', file: './interaction/select-highlight-in-range.mjs', bundles: ['vtable'] },
  { id: 'select-header-scroll-top', purpose: '滚动后固定表头仍可选择', file: './interaction/select-header-scroll-top.mjs', bundles: ['vtable'] },
  { id: 'api-update-columns-on-mouseleave', purpose: '鼠标离开单元格回调中更新列', file: './api/update-columns-on-mouseleave.mjs', bundles: ['vtable'] },
  { id: 'api-update-columns-after-selection', purpose: '点击选中时更新列并保持选区', file: './api/update-columns-after-selection.mjs', bundles: ['vtable'] },
  { id: 'layout-auto-fill-width-resize-container', purpose: '自动填宽下拖列边界和调整容器', file: './layout/auto-fill-width-resize-container.mjs', bundles: ['vtable'] },
  { id: 'double-click-auto-column-width', purpose: '拖宽后双击边界自动测量列宽', file: './interaction/double-click-auto-column-width.mjs', bundles: ['vtable'] },
  { id: 'double-click-auto-width-height', purpose: '自动行高换行时双击测量列宽', file: './interaction/double-click-auto-width-height.mjs', bundles: ['vtable'] },
  { id: 'plugin-auto-fill-grid-tree-origin-value', purpose: '树形表头填充柄拖动复制原值', file: './plugins/auto-fill-grid-tree-origin-value.mjs', bundles: ['plugins'] },
  { id: 'checkbox-over-thousand-rows', purpose: '千行外滚动与冻结复选格点击', file: './cells/checkbox-over-thousand-rows.mjs', bundles: ['vtable'] },
  { id: 'pivot-update-sort-rules-after-click', purpose: '透视排序图标点击后替换行列规则', file: './pivot/update-sort-rules-after-click.mjs', bundles: ['vtable'] },
  { id: 'pivot-chart-brush-multiple-selection', purpose: '双透视柱状图 multiple 框选拖动', file: './pivot-chart/brush-multiple-selection.mjs', bundles: ['vchart'] },
  { id: 'api-change-cell-values', purpose: '二维批量更新单元格值', file: './api/change-cell-values.mjs', bundles: ['vtable'] },
  { id: 'pivot-wide-scrollbar', purpose: '透视表宽滚动条与主题条纹', file: './scroll/pivot-wide-rail.mjs', bundles: ['vtable'] },
  { id: 'edit-complete-input', purpose: '输入编辑器完成提交', file: './edit/complete-input.mjs', bundles: ['editors'] },
  { id: 'select-disabled-column-range', purpose: '拖选不能覆盖禁选列', file: './interaction/disabled-column-range.mjs', bundles: ['vtable'] },
  { id: 'sheet-add-rows', purpose: 'Sheet 行高调整与插入记录', file: './sheet/add-rows.mjs', bundles: ['sheet'] },
  { id: 'sheet-insert-columns-before-second', purpose: 'Sheet 第二列前插入两列', file: './sheet/insert-columns-before-second.mjs', bundles: ['sheet'] },
  { id: 'sheet-insert-columns-before-third', purpose: 'Sheet 第三列前插入两列', file: './sheet/insert-columns-before-third.mjs', bundles: ['sheet'] },
  { id: 'sheet-insert-rows-at-start', purpose: 'Sheet 第一条记录前插入两行', file: './sheet/insert-rows-at-start.mjs', bundles: ['sheet'] },
  { id: 'sheet-insert-rows-after-first', purpose: 'Sheet 第二条记录前插入两行', file: './sheet/insert-rows-after-first.mjs', bundles: ['sheet'] },
  { id: 'pivot-no-indicators', purpose: '无指标透视表与链接型维度表头', file: './pivot/no-indicators.mjs', bundles: ['vtable'] },
  { id: 'keyboard-select-all-body', purpose: '快捷键全选表体且排除表头', file: './keyboard/select-all-body.mjs', bundles: ['vtable'] },
  { id: 'pivot-tree-zero-expand', purpose: '数字零值透视树节点展开', file: './pivot/tree-zero-expand.mjs', bundles: ['vtable'] },
  { id: 'plugin-master-detail-auto-height', purpose: '主从表自动高度与滚动', file: './plugins/master-detail-auto-height.mjs', bundles: ['plugins'] },
  { id: 'frozen-one-column-left', purpose: '唯一列左冻结边界', file: './frozen/one-column-left.mjs', bundles: ['vtable'] },
  { id: 'frozen-one-column-right', purpose: '唯一列右冻结边界', file: './frozen/one-column-right.mjs', bundles: ['vtable'] },
  { id: 'frozen-top-bottom-border', purpose: '上下冻结行与四边框', file: './frozen/top-bottom-border.mjs', bundles: ['vtable'] },
  { id: 'header-hidden-nested', purpose: '三级分组表头末级列隐藏', file: './header/hidden-nested.mjs', bundles: ['vtable'] },
  { id: 'style-border-clip-direction', purpose: '单元格边框裁剪方向', file: './style/border-clip-direction.mjs', bundles: ['vtable'] },
  { id: 'records-delete-all-bottom-frozen', purpose: '删除全部记录后底部冻结区重置', file: './records/delete-all-bottom-frozen.mjs', bundles: ['vtable'] },
  { id: 'records-array-path-add', purpose: '数组记录字段路径与插入', file: './records/array-path-add.mjs', bundles: ['vtable'] },
  { id: 'layout-container-fit-height', purpose: 'autoWidth 与容器高度适配', file: './layout/container-fit-height.mjs', bundles: ['vtable'] },
  { id: 'pivot-calculated-field-hidden-dependencies', purpose: '未显示依赖指标的计算字段', file: './pivot/calculated-field-hidden-dependencies.mjs', bundles: ['vtable'] },
  { id: 'gantt-project-range-set-records', purpose: 'setRecords 项目时间边界重算', file: './gantt/project-range-set-records.mjs', bundles: ['gantt'] },
  { id: 'gantt-empty-mark-line', purpose: '无任务的固定日期标记线', file: './gantt/empty-mark-line.mjs', bundles: ['gantt'] },
  { id: 'gantt-resize-task-list-header', purpose: 'Gantt 缩窄任务列表列头后双层时间轴保持布局', file: './gantt/resize-task-list-header.mjs', bundles: ['gantt'] },
  { id: 'gantt-baseline-overlap', purpose: '基线与任务条重叠布局', file: './gantt/baseline-overlap.mjs', bundles: ['gantt'] },
  { id: 'pivot-chart-heatmap-two-indicators', purpose: '双热力图数据流和颜色图例', file: './pivot-chart/heatmap-two-indicators.mjs', bundles: ['vchart'] },
  { id: 'sheet-update-option', purpose: 'Sheet 全量配置更新', file: './sheet/update-option.mjs', bundles: ['sheet'] },
  { id: 'pivot-chart-box-plot-horizontal', purpose: '水平箱线图与离群点', file: './pivot-chart/box-plot-horizontal.mjs', bundles: ['vchart'] },
  { id: 'pivot-chart-histogram-overlap', purpose: '重叠区间透视直方图', file: './pivot-chart/histogram-overlap.mjs', bundles: ['vchart'] },
  { id: 'theme-dark-icons', purpose: '深色主题的冻结与排序图标', file: './theme/dark-icons.mjs', bundles: ['vtable'] },
  { id: 'plugin-fill-handle-hit-area', purpose: '填充柄视觉大小和命中范围', file: './plugins/fill-handle-hit-area.mjs', bundles: ['vtable'] },
  { id: 'pivot-update-option-row-header-width', purpose: '透视配置更新后行头列宽', file: './pivot/update-option-row-header-width.mjs', bundles: ['vtable'] },
  { id: 'pivot-custom-merge-subtotal', purpose: '行头自定义合并和小计', file: './pivot/custom-merge-subtotal.mjs', bundles: ['vtable'] },
  { id: 'sheet-copy-paste', purpose: 'Sheet 公式结果事件复制粘贴', file: './sheet/copy-paste.mjs', bundles: ['sheet'] },
  { id: 'keyboard-copy-paste-event', purpose: '列表单格事件复制粘贴', file: './keyboard/copy-paste-event.mjs', bundles: ['vtable'] },
  { id: 'sort-multiple-header-click', purpose: '多字段排序图标连续点击', file: './sort/multiple-header-click.mjs', bundles: ['vtable'] },
  { id: 'pivot-chart-scatter-axes', purpose: 'bar 与 scatter 独立轴', file: './pivot-chart/scatter-axes.mjs', bundles: ['vchart'] },
  { id: 'theme-update-theme', purpose: 'ARCO 主题运行时更新', file: './theme/update-theme.mjs', bundles: ['vtable'] },
  { id: 'header-sort-icon-hidden', purpose: '可排序列隐藏排序图标', file: './header/sort-icon-hidden.mjs', bundles: ['vtable'] },
  { id: 'plugin-context-menu-click', purpose: '上下文菜单冻结事件', file: './plugins/context-menu-click.mjs', bundles: ['plugins'] },
  { id: 'layout-container-fit-both', purpose: 'autoWidth 与布尔容器适配', file: './layout/container-fit-both.mjs', bundles: ['vtable'] },
  { id: 'header-hidden-parent', purpose: '隐藏父表头保留独立同字段列', file: './header/hidden-parent.mjs', bundles: ['vtable'] },
  { id: 'style-underline', purpose: '下划线变体与虚线边框', file: './style/underline.mjs', bundles: ['vtable'] },
  { id: 'transpose-update-option-off', purpose: '转置记录更新后关闭转置', file: './transpose/update-option-off.mjs', bundles: ['vtable'] },
  { id: 'records-add-sorted', purpose: '排序状态下批量插入缺字段记录', file: './records/add-sorted.mjs', bundles: ['vtable'] },
  { id: 'records-delete-sorted', purpose: '排序状态下双索引删除记录', file: './records/delete-sorted.mjs', bundles: ['vtable'] },
  { id: 'component-legend-resize', purpose: '单行图例和标题随容器缩窄', file: './components/legend-resize.mjs', bundles: ['vtable'] },
  { id: 'frozen-short-content-connected', purpose: '短内容上下冻结区连接边界', file: './frozen/short-content-connected.mjs', bundles: ['vtable'] },
  { id: 'tree-checkbox-set-state', purpose: '树节点复选状态设置且不级联', file: './tree/checkbox-set-state.mjs', bundles: ['vtable'] },
  { id: 'pivot-indicator-sort-subtotal', purpose: '指标路径排序与行维度小计', file: './pivot/indicator-sort-subtotal.mjs', bundles: ['vtable'] },
  { id: 'pivot-aggregation-rules', purpose: 'SUM COUNT AVG 三类聚合指标', file: './pivot/aggregation-rules.mjs', bundles: ['vtable'] },
  { id: 'header-grid-tree', purpose: '普通列表 grid-tree 分组表头', file: './header/grid-tree.mjs', bundles: ['vtable'] },
  { id: 'header-grid-tree-transpose', purpose: '转置 grid-tree 分组表头', file: './header/grid-tree-transpose.mjs', bundles: ['vtable'] },
  { id: 'menu-dropdown-highlight', purpose: '列下拉菜单状态图标与高亮', file: './menu/dropdown-highlight.mjs', bundles: ['vtable'] },
  { id: 'gantt-baseline-padding-static', purpose: 'Gantt 任务条和基线的固定纵向间距', file: './gantt/baseline-padding-static.mjs', bundles: ['gantt'] },
  { id: 'gantt-baseline-padding-function', purpose: 'Gantt 任务索引驱动的动态基线间距', file: './gantt/baseline-padding-function.mjs', bundles: ['gantt'] },
  { id: 'pivot-chart-mark-line', purpose: '柱状图汇总标记线与端点符号', file: './pivot-chart/mark-line.mjs', bundles: ['vchart'] },
  { id: 'pivot-chart-combination-forecast', purpose: '双指标历史柱趋势线预测柱组合图', file: './pivot-chart/combination-forecast.mjs', bundles: ['vchart'] },
  { id: 'pivot-chart-sunburst-hierarchy', purpose: '嵌套层级数据旭日图', file: './pivot-chart/sunburst-hierarchy.mjs', bundles: ['vchart'] },
  { id: 'header-grid-tree-filter-expand', purpose: '筛选插件与三级树形表头点击展开', file: './header/grid-tree-filter-expand.mjs', bundles: ['plugins'] },
  { id: 'promise-custom-merge', purpose: '异步批次数据中的多行多列自定义合并', file: './data/promise-custom-merge.mjs', bundles: ['vtable'] },
  { id: 'tree-checkbox-add-record', purpose: '树形行序号复选状态下插入根记录', file: './tree/checkbox-add-record.mjs', bundles: ['vtable'] },
  { id: 'tree-checkbox-delete-record', purpose: '树形行序号复选状态下删除混合路径', file: './tree/checkbox-delete-record.mjs', bundles: ['vtable'] },
  { id: 'sheet-cross-tab-formula', purpose: '跨 Sheet 求和与中文感叹号归一化', file: './sheet/cross-tab-formula.mjs', bundles: ['sheet'] },
  { id: 'drag-column-header', purpose: '多层表头旁普通列鼠标拖动排序', file: './interaction/drag-column-header.mjs', bundles: ['vtable'] },
  { id: 'tree-lazy-record-children', purpose: '展开树节点后事件注入懒加载子记录', file: './tree/lazy-record-children.mjs', bundles: ['vtable'] },
  { id: 'records-add-pagination', purpose: '分页首屏内批量插入记录', file: './records/add-pagination.mjs', bundles: ['vtable'] },
  { id: 'pivot-update-sort-state-click', purpose: '透视排序点击事件回写专用状态', file: './pivot/update-pivot-sort-state-click.mjs', bundles: ['vtable'] },
  { id: 'pivot-chart-histogram-color', purpose: '直方图区间颜色域与零值柱', file: './pivot-chart/histogram-color.mjs', bundles: ['vchart'] },
  { id: 'gantt-locate-offscreen-task', purpose: 'Gantt 左右离屏任务定位图标点击滚动', file: './gantt/locate-offscreen-task.mjs', bundles: ['gantt'] },
  { id: 'tree-pagination-double-click', purpose: '树形列表第二页双击事件定位', file: './tree/pagination-double-click.mjs', bundles: ['vtable'] },
  { id: 'sheet-formula-auto-fill-copy', purpose: 'Sheet 公式填充柄拖动和复制填充菜单', file: './sheet/formula-auto-fill-copy.mjs', bundles: ['sheet'] },
  { id: 'select-disable-callback', purpose: '回调按行列禁选单元格', file: './interaction/disable-select-callback.mjs', bundles: ['vtable'] },
  { id: 'gantt-move-task-bar', purpose: 'Gantt 任务条拖动与日期事件', file: './gantt/move-task-bar.mjs', bundles: ['gantt'] },
  { id: 'pivot-initial-column-sort-state', purpose: '透视列树分支初始排序状态与自动填宽', file: './pivot/initial-column-sort-state.mjs', bundles: ['vtable'] },
  { id: 'blank-area-deselect', purpose: '空白区清除选择的双配置切换', file: './interaction/blank-area-deselect.mjs', bundles: ['vtable'] },
  { id: 'disabled-arrow-navigation', purpose: '禁选列与键盘方向导航', file: './keyboard/disabled-arrow-navigation.mjs', bundles: ['vtable'] },
  { id: 'pivot-custom-total-data-tree', purpose: '显式汇总记录的透视树展开', file: './pivot/custom-total-data-tree.mjs', bundles: ['vtable'] },
  { id: 'promise-keep-data', purpose: '异步数据源配置更新时保留数据', file: './data/promise-keep-data.mjs', bundles: ['vtable'] },
  { id: 'pivot-corner-empty-matrix', purpose: '透视表空行空列空指标角头矩阵', file: './pivot/corner-empty-matrix.mjs', bundles: ['vtable'] },
  { id: 'pivot-chart-bar-line-right-axis', purpose: '透视柱线图百分比柱宽与左右双轴', file: './pivot-chart/bar-line-right-axis.mjs', bundles: ['vchart'] },
  { id: 'tree-filter-clear-lazy', purpose: '树形列表过滤、懒加载与清除规则', file: './tree/filter-clear-lazy.mjs', bundles: ['vtable'] },
  { id: 'gantt-tree-move-resize', purpose: '树形子任务条移动与拉伸', file: './gantt/tree-move-resize.mjs', bundles: ['gantt'] },
  { id: 'group-add-delete-records', purpose: '两级分组内按路径增删记录', file: './group/add-delete-records.mjs', bundles: ['vtable'] },
  { id: 'drag-row-series-select', purpose: '行序号列纵向拖选', file: './interaction/drag-row-series-select.mjs', bundles: ['vtable'] },
  { id: 'drag-row-series-order', purpose: '行序号两次拖动重排记录', file: './interaction/drag-row-series-order.mjs', bundles: ['vtable'] },
  { id: 'keyboard-cut-paste-event', purpose: '事件剪贴板剪切两格并粘贴', file: './keyboard/cut-paste-event.mjs', bundles: ['vtable'] },
  { id: 'pivot-empty-string-dimension', purpose: '透视空字符串列维度与普通列并存', file: './pivot/empty-string-dimension.mjs', bundles: ['vtable'] },
  { id: 'pivot-chart-pie-multi-select', purpose: '透视饼图连续扇区多选', file: './pivot-chart/pie-multi-select.mjs', bundles: ['vchart'] },
  { id: 'resize-row-height', purpose: '列表选择后拖动行边界调整行高', file: './interaction/resize-row-height.mjs', bundles: ['vtable'] },
  { id: 'pivot-resize-indicator-row', purpose: '指标行上的透视表拖动行高', file: './pivot/resize-indicator-row.mjs', bundles: ['vtable'] },
  { id: 'pivot-corner-sort-one-dimension', purpose: '单级角头维度初始降序状态与排序图标', file: './pivot/corner-sort-one-dimension.mjs', bundles: ['vtable'] },
  { id: 'pivot-corner-sort-two-dimensions', purpose: '两级角头维度初始降序状态与排序图标', file: './pivot/corner-sort-two-dimensions.mjs', bundles: ['vtable'] },
  { id: 'pivot-chart-circle-packing-hierarchy', purpose: '透视圆形打包图层级数据', file: './pivot-chart/circle-packing-hierarchy.mjs', bundles: ['vchart'] },
  { id: 'layout-min-max-adaptive-width', purpose: '自适应列宽的最小最大值', file: './layout/min-max-adaptive-width.mjs', bundles: ['vtable'] },
  { id: 'pivot-max-frozen-width', purpose: '透视冻结行头宽度上限逐列裁剪', file: './frozen/pivot-max-frozen-width.mjs', bundles: ['vtable'] },
  { id: 'pivot-chart-crosshair-linkage-hover', purpose: '横向图表悬停准线联动', file: './pivot-chart/crosshair-linkage-hover.mjs', bundles: ['vchart'] },
  { id: 'pivot-column-header-title', purpose: '透视列表头独立标题行', file: './pivot/column-header-title.mjs', bundles: ['vtable'] },
  { id: 'sort-initial-multiple-state', purpose: 'setRecords 前设置复合初始排序', file: './sort/initial-multiple-state.mjs', bundles: ['vtable'] },
  { id: 'layout-limit-max-auto-width', purpose: '自动列宽最大值开关与数值限制', file: './layout/limit-max-auto-width.mjs', bundles: ['vtable'] },
  { id: 'layout-custom-compute-row-height', purpose: '按记录回调计算行高', file: './layout/custom-compute-row-height.mjs', bundles: ['vtable'] },
  { id: 'frozen-drag-disabled', purpose: '冻结列表头禁拖但普通列仍可移动', file: './frozen/drag-disabled.mjs', bundles: ['vtable'] },
  { id: 'frozen-drag-adjust-count', purpose: '拖动普通列进入冻结区并调整冻结列数', file: './frozen/drag-adjust-count.mjs', bundles: ['vtable'] },
  { id: 'frozen-scroll-columns', purpose: '左右冻结区独立横向滚动', file: './frozen/scroll-frozen-columns.mjs', bundles: ['vtable'] },
  { id: 'tree-checkbox-record-index-clear', purpose: '隐藏树子节点索引取消勾选后清空整列', file: './tree/checkbox-record-index-clear.mjs', bundles: ['vtable'] },
  { id: 'layout-canvas-size-options', purpose: '固定自动限制及更新后的画布尺寸', file: './layout/canvas-size-options.mjs', bundles: ['vtable'] },
  { id: 'tree-zero-height-toggle', purpose: '零高度树子行折叠展开后视口填充', file: './tree/zero-height-toggle.mjs', bundles: ['vtable'] },
  { id: 'pivot-corner-remaining-variants', purpose: '角头其余三种行列指标排列', file: './pivot/corner-remaining-variants.mjs', bundles: ['vtable'] },
  { id: 'pivot-resize-indicator-group', purpose: '指标组行高按比例一起拖动', file: './pivot/resize-indicator-group.mjs', bundles: ['vtable'] },
  { id: 'transpose-only-body-auto-width', purpose: '转置表仅按表体计算自动列宽', file: './transpose/only-body-auto-width.mjs', bundles: ['vtable'] },
  { id: 'hover-cross', purpose: '表头与表体悬停的 cross 高亮模式', file: './interaction/hover-cross.mjs', bundles: ['vtable'] },
  { id: 'hover-row', purpose: '表头与表体悬停的 row 高亮模式', file: './interaction/hover-row.mjs', bundles: ['vtable'] },
  { id: 'hover-column', purpose: '表头与表体悬停的 column 高亮模式', file: './interaction/hover-column.mjs', bundles: ['vtable'] },
  { id: 'hover-single', purpose: '表头与表体悬停的 single 高亮模式', file: './interaction/hover-single.mjs', bundles: ['vtable'] },
  { id: 'select-drag-outside', purpose: '连续单选拖选表头选择与表外清选', file: './interaction/select-drag-outside.mjs', bundles: ['vtable'] },
  { id: 'select-header-cell', purpose: '表头 cell 模式单格选择', file: './interaction/select-header-cell.mjs', bundles: ['vtable'] },
  { id: 'select-column-disabled', purpose: '列级表体与表头禁选', file: './interaction/select-column-disabled.mjs', bundles: ['vtable'] },
  { id: 'select-global-disabled', purpose: '全局禁选表体与表头', file: './interaction/select-global-disabled.mjs', bundles: ['vtable'] },
  { id: 'select-header-disabled-drag', purpose: '表头禁选下的表体选择与列拖动', file: './interaction/select-header-disabled-drag.mjs', bundles: ['vtable'] },
  { id: 'frozen-shadow-start', purpose: '冻结列 overflow 阴影在 start 位置的可见性', file: './frozen/frozen-shadow-start.mjs', bundles: ['vtable'] },
  { id: 'frozen-shadow-end', purpose: '冻结列 overflow 阴影在 end 位置的可见性', file: './frozen/frozen-shadow-end.mjs', bundles: ['vtable'] },
  { id: 'frozen-shadow-middle', purpose: '冻结列 overflow 阴影在 middle 位置的可见性', file: './frozen/frozen-shadow-middle.mjs', bundles: ['vtable'] },
  { id: 'scrollbar-ignore-frozen', purpose: '主横向滚动条跨越冻结列宽度', file: './frozen/scrollbar-ignore-frozen.mjs', bundles: ['vtable'] },
  { id: 'frozen-empty-records-header', purpose: '大量列滚动后清空记录保留冻结表头', file: './frozen/empty-records-header.mjs', bundles: ['vtable'] },
  { id: 'checkbox-header-options', purpose: '复选框表头回调固定选中与禁用配置', file: './cells/checkbox-header-options.mjs', bundles: ['vtable'] },
  { id: 'link-merged-auto-height', purpose: '合并链接单元格在自动行高下禁用点击跳转', file: './cells/link-merged-auto-height.mjs', bundles: ['vtable'] },
  { id: 'pivot-indicator-hide-frozen', purpose: '按列隐藏透视指标并冻结右列与底行', file: './pivot/indicator-hide-frozen.mjs', bundles: ['vtable'] },
  { id: 'pivot-color-legend-order', purpose: '透视表标题先于顶部连续色彩图例布局', file: './pivot/color-legend-order.mjs', bundles: ['vtable'] },
  { id: 'pivot-chart-spec-mark-line', purpose: '透视表回调图表配置及面积图阈值标记线', file: './pivot/chart-spec-mark-line.mjs', bundles: ['vchart'] },
  { id: 'pivot-chart-area-axis-sort', purpose: '启用坐标轴排序配置的双系列透视面积图', file: './pivot-chart/area-axis-sort.mjs', bundles: ['vchart'] },
  { id: 'pivot-chart-rose-indicator-title', purpose: '透视玫瑰图与可见指标标题', file: './pivot-chart/rose-indicator-title.mjs', bundles: ['vchart'] },
  { id: 'plugin-excel-delete-range', purpose: 'Excel 键盘插件通过 Delete 清空可编辑选区', file: './plugins/excel-delete-range.mjs', bundles: ['plugins', 'editors'] },
];

/** 从当前清单目录加载用例，冻结副本不会回到工作区取代码。 */
export async function loadCase(item) {
  return (await import(new URL(item.file, import.meta.url))).default;
}
