export const mockData = [
  {
    'Row ID': '7981',
    'Order ID': '1',
    'Order Date': '2015/1/3',
    'Ship Date': '2015/1/7',
    'Ship Mode': 'Standard Class',
    'Customer ID': 'DP-13000',
    'Customer Name': 'Darren Powers',
    Segment: 'Consumer',
    Country: 'United States',
    City: 'Houston',
    State: 'Texas',
    'Postal Code': '77095',
    Region: 'Central',
    'Product ID': 'OFF-PA-10000174',
    Category: 'Office Supplies',
    'Sub-Category': 'Paper',
    'Product Name': 'Message Book, Wirebound, Four 5 1/2" X 4" Forms/Pg., 200 Dupl. Sets/Book',
    Sales: -16.448,
    Quantity: '2',
    Discount: '0.2',
    Profit: '5.5512'
  },
  {
    'Row ID': '740',
    'Order ID': '2',
    'Order Date': '2015/1/4',
    'Ship Date': '2015/1/8',
    'Ship Mode': 'Standard Class',
    'Customer ID': null,
    'Customer Name': 'Phillina Ober',
    Segment: 'Home Office',
    Country: 'United States',
    City: 'Naperville',
    State: 'Illinois',
    'Postal Code': '60540',
    Region: 'Central',
    'Product ID': 'OFF-LA-10003223',
    Category: 'Office Supplies',
    'Sub-Category': 'Labels',
    'Product Name': 'Avery 508',
    Sales: 11.784,
    Quantity: '3',
    Discount: '0.2',
    Profit: '4.2717'
  },
  {
    'Row ID': '741',
    'Order ID': 'CA-2015-112326',
    'Order Date': '2015/1/4',
    'Ship Date': '2015/1/8',
    'Ship Mode': 'Standard Class',
    'Customer ID': '1',
    'Customer Name': 'Phillina Ober',
    Segment: 'Home Office',
    Country: 'United States',
    City: 'Naperville',
    State: 'Illinois',
    'Postal Code': '60540',
    Region: 'Central',
    'Product ID': 'OFF-ST-10002743',
    Category: 'Office Supplies',
    'Sub-Category': 'Storage',
    'Product Name': 'SAFCO Boltless Steel Shelving',
    Sales: 272.736,
    Quantity: '3',
    Discount: '0.2',
    Profit: '-64.7748'
  },
  {
    'Row ID': '742',
    'Order ID': 'CA-2015-112326',
    'Order Date': '2015/1/4',
    'Ship Date': '2015/1/8',
    'Ship Mode': 'Standard Class',
    'Customer ID': '2',
    'Customer Name': 'Phillina Ober',
    Segment: 'Home Office',
    Country: 'United States',
    City: 'Naperville',
    State: 'Illinois',
    'Postal Code': '60540',
    Region: 'Central',
    'Product ID': 'OFF-BI-10004094',
    Category: 'Office Supplies',
    'Sub-Category': 'Binders',
    'Product Name': 'GBC Standard Plastic Binding Systems Combs',
    Sales: 3.54,
    Quantity: '2',
    Discount: '0.8',
    Profit: '-5.487'
  },
  {
    'Row ID': '1760',
    'Order ID': 'CA-2015-141817',
    'Order Date': '2015/1/5',
    'Ship Date': '2015/1/12',
    'Ship Mode': 'Standard Class',
    'Customer ID': null,
    'Customer Name': 'Mick Brown',
    Segment: 'Consumer',
    Country: 'United States',
    City: 'Philadelphia',
    State: 'Pennsylvania',
    'Postal Code': '19143',
    Region: 'East',
    'Product ID': 'OFF-AR-10003478',
    Category: 'Office Supplies',
    'Sub-Category': 'Art',
    'Product Name': 'Avery Hi-Liter EverBold Pen Style Fluorescent Highlighters, 4/Pack',
    Sales: 19.536,
    Quantity: '3',
    Discount: '0.2',
    Profit: '4.884'
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {}
];
